"""Restore scanning models

Revision ID: 2d23fe1445f9
Revises: c78a749dd40d
Create Date: 2026-05-29 00:47:03.030672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d23fe1445f9'
down_revision: Union[str, None] = 'c78a749dd40d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_discovery_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_job_id', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('os_name', sa.String(), nullable=True),
    sa.Column('os_family', sa.String(), nullable=True),
    sa.Column('os_accuracy', sa.String(), nullable=True),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('open_ports', sa.JSON(), nullable=True),
    sa.Column('web_apps', sa.JSON(), nullable=True),
    sa.Column('containers', sa.JSON(), nullable=True),
    sa.Column('cloud_instance', sa.JSON(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_discovery_results_id'), 'asset_discovery_results', ['id'], unique=False)
    op.create_index(op.f('ix_asset_discovery_results_scan_job_id'), 'asset_discovery_results', ['scan_job_id'], unique=False)
    op.create_table('port_scan_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_job_id', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('extrainfo', sa.String(), nullable=True),
    sa.Column('cpe', sa.String(), nullable=True),
    sa.Column('banner', sa.Text(), nullable=True),
    sa.Column('scan_method', sa.String(), nullable=True),
    sa.Column('risk', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('scripts', sa.JSON(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_port_scan_results_id'), 'port_scan_results', ['id'], unique=False)
    op.create_index(op.f('ix_port_scan_results_scan_job_id'), 'port_scan_results', ['scan_job_id'], unique=False)
    op.create_table('port_scan_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_job_id', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('os_name', sa.String(), nullable=True),
    sa.Column('os_family', sa.String(), nullable=True),
    sa.Column('os_accuracy', sa.String(), nullable=True),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('total_open_ports', sa.Integer(), nullable=True),
    sa.Column('tcp_open', sa.Integer(), nullable=True),
    sa.Column('udp_open', sa.Integer(), nullable=True),
    sa.Column('critical_ports', sa.Integer(), nullable=True),
    sa.Column('high_risk_ports', sa.Integer(), nullable=True),
    sa.Column('overall_risk', sa.String(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_port_scan_summaries_id'), 'port_scan_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_port_scan_summaries_scan_job_id'), 'port_scan_summaries', ['scan_job_id'], unique=False)
    op.create_table('service_fingerprint_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_job_id', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('extrainfo', sa.String(), nullable=True),
    sa.Column('cpe', sa.String(), nullable=True),
    sa.Column('banner', sa.Text(), nullable=True),
    sa.Column('http_server', sa.String(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_fingerprint_results_id'), 'service_fingerprint_results', ['id'], unique=False)
    op.create_index(op.f('ix_service_fingerprint_results_scan_job_id'), 'service_fingerprint_results', ['scan_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_fingerprint_results_scan_job_id'), table_name='service_fingerprint_results')
    op.drop_index(op.f('ix_service_fingerprint_results_id'), table_name='service_fingerprint_results')
    op.drop_table('service_fingerprint_results')
    op.drop_index(op.f('ix_port_scan_summaries_scan_job_id'), table_name='port_scan_summaries')
    op.drop_index(op.f('ix_port_scan_summaries_id'), table_name='port_scan_summaries')
    op.drop_table('port_scan_summaries')
    op.drop_index(op.f('ix_port_scan_results_scan_job_id'), table_name='port_scan_results')
    op.drop_index(op.f('ix_port_scan_results_id'), table_name='port_scan_results')
    op.drop_table('port_scan_results')
    op.drop_index(op.f('ix_asset_discovery_results_scan_job_id'), table_name='asset_discovery_results')
    op.drop_index(op.f('ix_asset_discovery_results_id'), table_name='asset_discovery_results')
    op.drop_table('asset_discovery_results')
    # ### end Alembic commands ###
