"""Add task_id to ScanJob

Revision ID: 3fa5157f8a48
Revises: 4d95c4a5470a
Create Date: 2026-05-26 11:19:41.134036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fa5157f8a48'
down_revision: Union[str, None] = '4d95c4a5470a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_jobs', sa.Column('task_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_jobs', 'task_id')
    # ### end Alembic commands ###
