"""Add anti-replay licensing controls

Revision ID: 46c325b99be8
Revises: 92c77d3d2bb7
Create Date: 2026-05-28 22:56:21.954597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46c325b99be8'
down_revision: Union[str, None] = '92c77d3d2bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licenses', sa.Column('license_id', sa.String(), nullable=True))
    op.add_column('licenses', sa.Column('machine_fingerprint', sa.String(), nullable=True))
    op.add_column('licenses', sa.Column('consumed', sa.Boolean(), nullable=True))
    op.add_column('licenses', sa.Column('consumed_at', sa.DateTime(), nullable=True))
    op.add_column('licenses', sa.Column('activation_hash', sa.Text(), nullable=True))
    op.create_index(op.f('ix_licenses_license_id'), 'licenses', ['license_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_licenses_license_id'), table_name='licenses')
    op.drop_column('licenses', 'activation_hash')
    op.drop_column('licenses', 'consumed_at')
    op.drop_column('licenses', 'consumed')
    op.drop_column('licenses', 'machine_fingerprint')
    op.drop_column('licenses', 'license_id')
    # ### end Alembic commands ###
