"""Add licensing models

Revision ID: 92c77d3d2bb7
Revises: 3fa5157f8a48
Create Date: 2026-05-28 14:03:59.683045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92c77d3d2bb7'
down_revision: Union[str, None] = '3fa5157f8a48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('license_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('license_key', sa.String(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_license_audit_logs_id'), 'license_audit_logs', ['id'], unique=False)
    op.create_table('licenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_key', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('features', sa.String(), nullable=True),
    sa.Column('max_scans', sa.Integer(), nullable=True),
    sa.Column('max_assets', sa.Integer(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licenses_id'), 'licenses', ['id'], unique=False)
    op.create_index(op.f('ix_licenses_license_key'), 'licenses', ['license_key'], unique=True)
    op.create_table('revoked_licenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_key', sa.String(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoked_licenses_id'), 'revoked_licenses', ['id'], unique=False)
    op.create_index(op.f('ix_revoked_licenses_license_key'), 'revoked_licenses', ['license_key'], unique=True)
    op.create_table('license_activations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_ping', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_license_activations_device_id'), 'license_activations', ['device_id'], unique=False)
    op.create_index(op.f('ix_license_activations_id'), 'license_activations', ['id'], unique=False)
    op.drop_index('ix_service_fingerprint_results_id', table_name='service_fingerprint_results')
    op.drop_index('ix_service_fingerprint_results_scan_job_id', table_name='service_fingerprint_results')
    op.drop_table('service_fingerprint_results')
    op.drop_index('ix_asset_discovery_results_id', table_name='asset_discovery_results')
    op.drop_index('ix_asset_discovery_results_scan_job_id', table_name='asset_discovery_results')
    op.drop_table('asset_discovery_results')
    op.drop_index('ix_port_scan_results_id', table_name='port_scan_results')
    op.drop_index('ix_port_scan_results_scan_job_id', table_name='port_scan_results')
    op.drop_table('port_scan_results')
    op.drop_index('ix_port_scan_summaries_id', table_name='port_scan_summaries')
    op.drop_index('ix_port_scan_summaries_scan_job_id', table_name='port_scan_summaries')
    op.drop_table('port_scan_summaries')
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=False)
    op.alter_column('vulnerabilities', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'Open'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vulnerabilities', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'Open'::character varying"))
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.create_table('port_scan_summaries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scan_job_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hostname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('os_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('os_family', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('os_accuracy', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('device_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total_open_ports', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tcp_open', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('udp_open', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('critical_ports', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('high_risk_ports', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('overall_risk', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('discovered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], name='port_scan_summaries_scan_job_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='port_scan_summaries_pkey')
    )
    op.create_index('ix_port_scan_summaries_scan_job_id', 'port_scan_summaries', ['scan_job_id'], unique=False)
    op.create_index('ix_port_scan_summaries_id', 'port_scan_summaries', ['id'], unique=False)
    op.create_table('port_scan_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scan_job_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('port', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('protocol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('service', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('product', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('extrainfo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cpe', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('banner', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('scan_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('risk', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('scripts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('discovered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], name='port_scan_results_scan_job_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='port_scan_results_pkey')
    )
    op.create_index('ix_port_scan_results_scan_job_id', 'port_scan_results', ['scan_job_id'], unique=False)
    op.create_index('ix_port_scan_results_id', 'port_scan_results', ['id'], unique=False)
    op.create_table('asset_discovery_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scan_job_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hostname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mac_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vendor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('os_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('os_family', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('os_accuracy', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('device_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('open_ports', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('web_apps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('containers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('cloud_instance', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('discovered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], name='asset_discovery_results_scan_job_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='asset_discovery_results_pkey')
    )
    op.create_index('ix_asset_discovery_results_scan_job_id', 'asset_discovery_results', ['scan_job_id'], unique=False)
    op.create_index('ix_asset_discovery_results_id', 'asset_discovery_results', ['id'], unique=False)
    op.create_table('service_fingerprint_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scan_job_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('port', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('protocol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('service', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('product', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('extrainfo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cpe', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('banner', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('http_server', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('discovered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], name='service_fingerprint_results_scan_job_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='service_fingerprint_results_pkey')
    )
    op.create_index('ix_service_fingerprint_results_scan_job_id', 'service_fingerprint_results', ['scan_job_id'], unique=False)
    op.create_index('ix_service_fingerprint_results_id', 'service_fingerprint_results', ['id'], unique=False)
    op.drop_index(op.f('ix_license_activations_id'), table_name='license_activations')
    op.drop_index(op.f('ix_license_activations_device_id'), table_name='license_activations')
    op.drop_table('license_activations')
    op.drop_index(op.f('ix_revoked_licenses_license_key'), table_name='revoked_licenses')
    op.drop_index(op.f('ix_revoked_licenses_id'), table_name='revoked_licenses')
    op.drop_table('revoked_licenses')
    op.drop_index(op.f('ix_licenses_license_key'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_id'), table_name='licenses')
    op.drop_table('licenses')
    op.drop_index(op.f('ix_license_audit_logs_id'), table_name='license_audit_logs')
    op.drop_table('license_audit_logs')
    # ### end Alembic commands ###
