"""Add is_archived to ScanJob

Revision ID: c78a749dd40d
Revises: 46c325b99be8
Create Date: 2026-05-28 23:39:50.777588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c78a749dd40d'
down_revision: Union[str, None] = '46c325b99be8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_jobs', sa.Column('is_archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_jobs', 'is_archived')
    # ### end Alembic commands ###
